# http://man.openbsd.org/OpenBSD-current/man1/tmux.1
# https://tmuxcheatsheet.com/

# Change your prefix from C-b to C-a.
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -as terminal-overrides ",xterm-256color:RGB"

# c-a c-a for the last active window
bind-key C-a last-window

# Set the base index from which an unused index should be searched when a new window is created.
# The default is zero.
set -g base-index 1

# Like base-index, but set the starting index for pane numbers.
set -g pane-base-index 1

# to prevent holes in window numbering after closing windows
set -g renumber-windows on

# faster command sequences
set -s escape-time 0

# Set the amount of time for which status line messages and other on-screen indicators are displayed.
# If set to 0, messages and indicators are displayed until a key is pressed. time is in milliseconds.
set -g display-time 10000

# aggressive resize
set -g window-size latest

setw -g status-style fg=black,bg=white
setw -g window-status-current-style fg=white,bg=blue
setw -g window-status-last-style fg=blue
setw -g window-status-activity-style bg=brightblack,fg=white

# set -g status-right-length 50
set -g status-right "\
 #[fg=darkgreen]#(cut -d' ' -f1-3 /proc/loadavg)\
 #[bg=brightblack]\
 #[bg=default,fg=black] %H:%M\
 #[bg=brightblack,fg=white] #{user}@#{host}:#{session_name} "
set -g status-left ''

setw -g window-status-separator ''
setw -g window-status-format ' \
#{window_index}\
#[fg=red]:#[fg=default]\
#{pane_current_command}\
#[fg=black]#{window_flags} '
setw -g window-status-current-format ' \
#{window_index}\
#[fg=black]:#[fg=default]\
#{pane_current_command}\
#[fg=black]#{window_flags} '

# border colors
set -g pane-border-style fg=green
set -g pane-active-border-style "bg=green fg=white"

# Set the default terminal for new windows created in this session - the default value of the TERM environment variable.
# For tmux to work correctly, this must be set to ‘screen’, ‘tmux’ or a derivative of them.
set -g default-terminal "tmux-256color"

# Set the maximum number of lines held in window history. This setting applies only to new windows.
# Existing window histories are not resized and retain the limit at the point they were created.
set -g history-limit 50000

# If on, tmux captures the mouse and allows mouse events to be bound as key bindings.
# See the MOUSE SUPPORT section for details.
set -g mouse off

# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# reload config file with C-a S-r
bind R source-file ~/.config/tmux/tmux.conf\; display-message "config reloaded"

# to get shift+arrows and ctrl+arrows working
setw -g xterm-keys on

# show activity in status line
set -g monitor-activity on
set -g visual-activity off
